services:
  polyflow:
    build: .
    container_name: polyflow-app
    restart: always
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=postgresql://polyflow:polyflow@polyflow-db:5434/polyflow
      - AUTH_SECRET=fepLqZqIvj0QTj1l5RLZuQqngB8wiC2QUke/jm3hpxc=
      - NEXTAUTH_URL=https://erp.nugrohopramono.my.id
      - NEXTAUTH_SECRET=fepLqZqIvj0QTj1l5RLZuQqngB8wiC2QUke/jm3hpxc=
    depends_on:
      - db
    networks:
      - default
      - ceritakita-network

  db:
    image: postgres:15-alpine
    container_name: polyflow-db
    restart: always
    environment:
      - POSTGRES_USER=polyflow
      - POSTGRES_PASSWORD=polyflow
      - POSTGRES_DB=polyflow
    command: -p 5434
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  ceritakita-network:
    external: true
    name: ceritakita-network
